apparmor: false
arch:
- aarch64
- amd64
description: 'Loki: like Prometheus, but for logs.'
homeassistant_api: true
image: ghcr.io/cedricziel/{arch}-addon-grafana-loki
init: false
map:
- share:rw
name: Grafana Loki
ports:
  3100/tcp: null
  9096/tcp: null
ports_description:
  3100/tcp: Loki
  9096/tcp: gRPC
slug: loki
url: https://github.com/cedricziel/ha-addon-grafana-mimir/blob/main/loki
version: 1.0.0
watchdog: http://[HOST]:3100/ready
