name: Grafana Loki
version: 1.2.1
slug: loki
description: 'Loki: like Prometheus, but for logs.'
url: https://github.com/cedricziel/ha-addons
startup: services
apparmor: false
ports:
  3100/tcp: null
  9096/tcp: null
ports_description:
  3100/tcp: Loki
  9096/tcp: gRPC
arch:
  - arm64
  - aarch64
  - amd64
  - armv7
init: false
map:
  - share:rw
homeassistant_api: true
image: ghcr.io/cedricziel/ha-addon-grafana-loki-{arch}
