---
channel: stable
addons:
  ha-addon-otelcol:
    repository: cedricziel/ha-addon-otelcol
    target: otelcol
    image: ghcr.io/cedricziel/ha-addon-otelcol/{arch}
  ha-addon-grafana-loki:
    repository: cedricziel/ha-addon-grafana-loki
    target: loki
    image: ghcr.io/cedricziel/ha-addon-grafana-loki/{arch}
  ha-addon-grafana-mimir:
    repository: cedricziel/ha-addon-grafana-mimir
    target: mimir
    image: ghcr.io/cedricziel/ha-addon-grafana-mimir/{arch}
  ha-addon-grafana-tempo:
    repository: cedricziel/ha-addon-grafana-tempo
    target: tempo
    image: ghcr.io/cedricziel/ha-addon-grafana-tempo/{arch}
