---
channel: stable
addons:
  otelcol:
    repository: cedricziel/ha-addon-otelcol
    target: otelcol
    image: ghcr.io/cedricziel/{arch}-ha-addon-otelcol
  loki:
    repository: cedricziel/ha-addon-grafana-loki
    target: loki
    image: ghcr.io/cedricziel/{arch}-addon-grafana-loki
  mimir:
    repository: cedricziel/ha-addon-grafana-mimir
    target: mimir
    image: ghcr.io/cedricziel/{arch}-ha-addon-grafana-mimir
  tempo:
    repository: cedricziel/ha-addon-grafana-tempo
    target: tempo
    image: ghcr.io/cedricziel/{arch}-addon-grafana-tempo
