---
channel: stable
addons:
  otelcol:
    repository: cedricziel/ha-addon-otelcol
    target: otelcol
    image: ghcr.io/cedricziel/{arch}-ha-addon-otelcol
  mimir:
    repository: cedricziel/ha-addon-grafana-mimir
    target: mimir
    image: ghcr.io/cedricziel/{arch}-addon-grafana-mimir
