---
channel: stable
addons:
  ha-addon-otelcol:
    repository: cedricziel/ha-addon-otelcol
    target: otelcol
    image: ghcr.io/cedricziel/ha-addon-otelcol/{arch}
  loki:
    repository: cedricziel/ha-addon-grafana-loki
    target: loki
    image: ghcr.io/cedricziel/ha-addon-grafana-loki/{arch}
  mimir:
    repository: cedricziel/ha-addon-grafana-mimir
    target: mimir
    image: ghcr.io/cedricziel/ha-addon-grafana-mimir/{arch}
  tempo:
    repository: cedricziel/ha-addon-grafana-tempo
    target: tempo
    image: ghcr.io/cedricziel/ha-addon-grafana-tempo/{arch}
