apparmor: false
arch:
- aarch64
- amd64
description: A scalable storage for prometheus
homeassistant_api: true
image: ghcr.io/cedricziel/{arch}-addon-grafana-mimir
init: false
map:
- share:rw
name: Grafana Mimir
options:
  scrape_ha: false
ports:
  8001/tcp: null
  9001/tcp: null
ports_description:
  8001/tcp: Mimir
  9001/tcp: gRPC
schema:
  scrape_ha: bool?
slug: mimir
url: https://github.com/cedricziel/ha-addon-grafana-mimir/blob/main/mimir
version: 1.0.0
watchdog: http://[HOST]:8001/ready
