name: Grafana Mimir
version: 1.0.4
slug: mimir
description: A scalable storage for prometheus
url: https://github.com/cedricziel/ha-addon-grafana-mimir/blob/main/mimir
apparmor: false
ports:
  8001/tcp: null
  9001/tcp: null
ports_description:
  8001/tcp: Mimir
  9001/tcp: gRPC
arch:
- aarch64
- amd64
init: false
map:
- share:rw
homeassistant_api: true
options:
  scrape_ha: false
schema:
  scrape_ha: bool?
image: ghcr.io/cedricziel/{arch}-addon-grafana-mimir
