name: OpenTelemetry Collector
version: 0.10.7
slug: otelcol
description: Bring the OpenTelemetry collector into your home
url: https://github.com/cedricziel/ha-addon-otelcol
ports:
  4317/tcp: null
  4318/tcp: null
ports_description:
  4317/tcp: OTLP/gRPC
  4318/tcp: OTLP/HTTP
arch:
- aarch64
- amd64
init: false
map:
- homeassistant_config:rw
- share:rw
apparmor: false
options:
  config: "receivers:\n  otlp:\n    protocols:\n      grpc:\n      http:\nprocessors:\n\
    \  batch:\nexporters:\n  logging:\n# health-check is activated by default\nextensions:\n\
    \  pprof:\n  zpages:\nservice:\n  extensions: [health_check,pprof,zpages]\n  pipelines:\n\
    \    traces:\n      receivers: [otlp]\n      processors: [batch]\n      exporters:\
    \ [logging]\n    metrics:\n      receivers: [otlp]\n      processors: [batch]\n\
    \      exporters: [logging]\n    logs:\n      receivers: [otlp]\n      processors:\
    \ [batch]\n      exporters: [logging]\n"
schema:
  config: str
image: ghcr.io/cedricziel/ha-addon-otelcol/{arch}
