---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ["update"]
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/repository-updater.yaml@main
    secrets:
      UPDATER_TOKEN: ${{ secrets.UPDATER_TOKEN }}
